고성능 서브셋 시스템
orioncactus/pretendard pull request #115
Opened 2023-01-12 03:52 UTC by black7375

### 주의 :warning: 

커다란 변경입니다.
- https://github.com/black7375/pretendard/tree/subset-gen-test
- https://github.com/black7375/pretendard/commit/e71770f64ca4df0c01cab8871306044ff9dc8df1

코드 리뷰와 생성된 폰트에 대한 테스트가 필요하다고 생각합니다. (cc @orioncactus @hiddenest)

### 환경
- 패키지들을 최신 버전으로 업데이트 했습니다. https://github.com/orioncactus/pretendard/commit/e6b2bb0a5b20dcb3ab0395fcd96233e9e0bfefd1
- [`.gitattributes`에 바이너리 파일 관련 설정](https://git-scm.com/book/ko/v2/Git%EB%A7%9E%EC%B6%A4-Git-Attributes) 추가

### 리팩토링
- [font-range의 v1.0.0](https://github.com/black7375/font-range/releases/tag/v1.0.0)에 자체적으로 글자 서브셋과 파이프라인 기능을 넣어 일관적으로 만들었습니다. https://github.com/orioncactus/pretendard/commit/42d9c41a4db071af9014f4f09f749b030457c72b
- 깃허브 액션들을 [나누어 재활용](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action)하였습니다. https://github.com/orioncactus/pretendard/commit/7651b75b5b9b81e151cee17bbafea43b7b23ac68

### 성능
- 분산 시스템: [깃허브 문서](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits)에 따르면 256개까지 생성가능하며, 동시 실행 가능한 작업은 MacOS가 5개, 나머지는 20개까지 입니다. https://github.com/orioncactus/pretendard/commit/7651b75b5b9b81e151cee17bbafea43b7b23ac68
  이 때 [맥OS만 3코어](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)이나 서브셋에 6개 이상씩 사용하기 위해 ubuntu를 사용했습니다.
- 워커 풀: font-range v1.0.0에서 워커풀을 사용해 계산 집약적 작업을 보다 효율적으로 하도록 만들었습니다. https://github.com/orioncactus/pretendard/commit/42d9c41a4db071af9014f4f09f749b030457c72b
- 쉘 생성 제거: font-range v1.0.0에서는 명령을 실행할 때 쉘 생성을 하지 않아 각 작업간 시작시간 지연을 줄였습니다. https://github.com/orioncactus/pretendard/commit/42d9c41a4db071af9014f4f09f749b030457c72b

### 기존 깃허브 액션과 비교

https://github.com/orioncactus/pretendard/actions/runs/3211271764
![image](https://user-images.githubusercontent.com/25581533/211969257-a9e818c4-46e1-4ff9-8201-4c93f1d4ea8f.png)

https://github.com/black7375/pretendard/actions/runs/3898790856
![image](https://user-images.githubusercontent.com/25581533/211969442-c5622150-8c5b-47bb-96b4-df7f7501c0de.png)

2023-01-13 01:13 UTC, sudosubin commented
가장 마지막으로 commit 한 사용자의 username과 email을 이용해 subset asset을 commit, push 하는 경우 몇 가지 문제가 예상되는데요,

- 사용자가 직접 commit 한 것인지, GitHub Workflows를 통해 자동으로 commit이 생성 되었는지 판단하기가 어려워집니다.
- 해당 사용자가 git commit gpg sign을 사용하는 경우, GitHub Workflows로 자동 생성된 commit은 gpg signing이 될 수 없습니다.
  - 근본적으로 해당 사용자 본인이 commit 하지 않았기 때문에 발생할 수 있는 문제입니다.
  - 사용자가 GitHub의 Vigilant mode를 사용하는 경우 해당 commit은 Unverified commit으로 남게 됩니다.

이런 이유로 `github-actions[bot]` 사용자로 commit, push 하는 것은 어떨까요? 필요한 경우에는 `Co-authored-by`를 통해 사용자를 표기할 수 있을 것 같습니다.

대부분의 커뮤니티에서도 GitHub Workflows에서 commit 하는 경우에는 `github-actions[bot]` 계정을 이용하고 있습니다.
https://github.com/orgs/community/discussions/26560#discussioncomment-3531273

한 번 확인해주시면 감사하겠습니다 🙇‍♂️

2023-01-13 01:28 UTC, black7375 commented
좋은 제안 감사합니다. 변경 후 force push 하도록 하겠습니다.

2023-01-13 01:39 UTC, black7375 commented on .github/workflows/generate.yml
> +        BRANCHES=("ori-1" "ori-2" "ori-3" "ori-4" "ori-5" "ori-6" "jp-1" "jp-2" "jp-3" "jp-4" "jp-5" "jp-6" "jp-7" "jp-8" "std-1")
실수로 `std-`라고 써져있던 점도 `std-1`으로 변경했습니다.

https://github.com/orioncactus/pretendard/compare/7651b75b5b9b81e151cee17bbafea43b7b23ac68..b6d9dd54f0c0161d28fd04be3e58b4a112438d2f

2023-01-17 16:44 UTC, orioncactus requested changes
주말에 확인하지 못하고 이제야 확인해보았습니다. 따로 테스트해보니 빌드 시간이 이전에는 80분 정도 걸리던 것이 7분 정도로 해결되어 너무나 기쁘고 설렙니다! 🥺 또 Co-authored도 정상적으로 작동했습니다.

다만 빌드에서 문제점이 있어 정리해보았습니다. 문제점은 두 가지며, 궁금한 점도 적어보았는데요, 시간이 되실 때 천천히 확인해주시면 감사하겠습니다!

---

### 문제
1. 모든 woff 확장자의 용량이 늘어났는데요, 확인해보니 글꼴 파일 구조 자체는 이전과 동일했고, fonttools에서 pyftsubset로 테스트해보니 `--with-zopfli` 옵션이 제외된 상황과 동일해서, 서브셋을 만드는 과정에서 `--with-zopfli` 옵션이 누락된 듯합니다.
2. 모든 다이나믹 서브셋이 woff는 2kb, woff2는 3kb로 생성됩니다. 모든 다이나믹 서브셋 파일 용량이 동일해서, css에서 unicode-range를 불러오지 못하는 것은 아닐까 예상해봅니다.

### 궁금한 점
- 커밋이 13개 정도로 분산되는데요, 여러 개로 분리되는 커밋을 하나로 묶는 방법이 있는지 궁금합니다. 각각 커밋들이 에셋을 만드는 동일한 목적을 가져서, 가능하면 하나로 묶어지면 좋지 않을까 싶은데, 조심스레 의견을 여쭤봅니다!

---

이렇게 멋진 서브셋 시스템으로 개선해주시고 더 나은 자동화에 기여해주셔서 다시 한번 감사드립니다! 저도 어떤 부분을 고쳐야 해결할 수 있는지는 이번주에 확인해보겠습니다.

2023-01-17 23:33 UTC, black7375 commented on .github/workflows/generate.yml
> +        done
1. --with-zopfli가 아직 적용이 안되었을거에요. 추후 적용하겠습니다
2. unicode-range 부분은 따로 확인을 해봐야 할 것 같네요
3. 이 부분에서 분산된 커밋을 하나로 묶어줄거에요

꼼꼼히 피드백 해주셔서 감사합니다
오늘부터 2박3일정도 놀러가서 컴퓨터에 접근을 못할듯하여 주말에 확인해보겠습니다ㅠㅠ

2023-01-18 15:00 UTC, orioncactus commented on .github/workflows/generate.yml
> +        done
확인해주셔서 감사드립니다! 물론 언제든지 괜찮습니다! 행복한 휴가 보내시고 시간되실 때 확인해주시면 감사하겠습니다 🥺 그동안 저도 확인해보고 알려드리겠습니다!

2023-01-23 00:28 UTC, black7375 commented on .github/workflows/generate.yml
> +        done
1,2번 관련하여 업데이트했습니다!!

2023-01-24 15:25 UTC, orioncactus commented on .github/workflows/generate.yml
> +        done
이렇게 꼼꼼하게 반영해주셔서 감사드립니다! 🤩 한 가지 부분만 제외하고 이전과 동일한 에셋으로 빌드되는 것을 확인했습니다 :fire:

#### 자잘한 이슈
1. 나머지는 모두 이상 없으나, 다이나믹 서브셋 woff 에셋에서 `--with-zopfli`이 적용되지 않은 듯합니다. 혹시 이 부분도 다시 확인해주실 수 있을지요? 제가 이 부분을 잘 알지 못해 도움을 여쭙습니다!

언제든 시간 되실 때 확인해주시면 너무나 감사하겠습니다! 천천히 확인해주셔도 너무나 괜찮습니다 🥺 Pretendard에 큰 도움을 주셔서 항상 감사드립니다! 🙇

2023-01-24 15:57 UTC, black7375 commented on .github/workflows/generate.yml
> +        done
어? 이상하네요. 한번 다시 확인해주실 수 있을까요?
일단 저같은 경우 `--with-zopfili`가 옵션값으로 들어오는 것 자체는 확인했습니다.

![image](https://user-images.githubusercontent.com/25581533/214342132-d59e8406-79be-4e6b-9ac3-691b37f0aa65.png)

---

다이나믹 woff에서 파일이 달라지긴 하나, 저같은 경우는 1.2MB에서 1.1MB로 크기가 줄어들었습니다.

![image](https://user-images.githubusercontent.com/25581533/214341492-7d5ec37c-27d2-4cd2-8cee-2c76f50bb500.png)
![image](https://user-images.githubusercontent.com/25581533/214341609-ac0af703-6ab8-40ef-91dd-1f1c2f90ddbe.png)

zopfli~=0.1.8에서 zopfli~=0.2.2로 버전 업데이트를 한 영향일 수도 있을 것 같아요.
저도 다시한번 확인해보겠습니다.

2023-01-25 14:57 UTC, orioncactus approved these changes

2023-01-25 15:04 UTC, black7375 commented on .github/workflows/generate.yml
> +        done
분산되는 커밋은 액션의  돌리면 자동으로 묶어줍니다. (처음부터 구현이 되어 있습니다!!)
혼동이 생기도록 이야기했었나봐요.

이 부분이 직전커밋과 `fix: Auto-generate assets`라는 메세지가 똑같다면 하나로 묶어주는데요,
```bash
if [[ "$(echo ${TWO_LOG} | head -1)" ==  "$(echo ${TWO_LOG} | tail -1)" ]]; then
  git reset --soft "HEAD~1"
  git commit --amend -m "${LOG}" -m "${LAST_COMMIT_AUTHOR}"
fi
```
1개의 커밋이 남을때까지 반복하는 방식입니다.

2023-02-05 18:02 UTC, orioncactus commented on .github/workflows/generate.yml
> +        done
예정보다 매우 늦게 답장드려 죄송합니다 🙇 밀린 작업을 마무리하고 이제야 확인했습니다!

이미 대응이 되어있는 것이었군요! 작동을 참고하실 수 있도록 branch를 따로 만들어 빌드를 테스트해보았습니다: https://github.com/orioncactus/pretendard/commits/test/subset-performance
보이는 것처럼 동일 메시지를 가진 커밋이 하나로 묶어지는 기능이 제대로 작동하지 않는 듯한데요, 혹시 이렇게 작동되는 게 맞는지 확인해주시면 너무나 감사하겠습니다! 업데이트가 필요한 파일이 많을 때는 같은 메시지를 가진 커밋이 13개가 나오기도 했어서, 의도대로 작동하는지 혹시나 하는 마음에 여쭤봅니다..!

또 이 PR을 merge할 때 이전과 마찬가지로 Create a merge commit으로 진행하면 될지도 알려주시면 감사하겠습니다! 이 두 부분만 확인되면 바로 merge하겠습니다!

2023-02-06 12:20 UTC, black7375 commented on .github/workflows/generate.yml
> +        done
헉!! 꼼꼼히 테스트 해주셔서 감사합니다.
`Co-authored` 메시지(`-m "${LAST_COMMIT_AUTHOR}"`)를 추가로 넣어 커밋 내용이 2줄 이상이 되면서 Git log 매칭이 부적절하게 되었네요.

첫번째 줄만 가져와 처리하도록 변경하였습니다.

---

제 생각에 변경내역이 많아서 merge 커밋으로 처리하는게 내역을 보기에 좋을 것 같아요.

2023-02-06 15:28 UTC, orioncactus commented on .github/workflows/generate.yml
> +        done
와우! 이렇게 해결 가능한 것이었군요! 항상 배워갑니다! 수정해주신대로 빌드를 테스트해보고 확인해보았는데, 하나로 잘 묶여지네요 🤩

이제 모두 문제 없이 작동하고, 마무리가 된 듯해 오늘인 2월 7일 늦은 밤이나 새벽에 말씀하신대로 Create a merge commit으로 merge하겠습니다!

---

### 마지막 질문
마지막으로 버전 태그 관련인데요, merge 이후에 바로 버전 태그를 붙이면 좋을지, 또는 다음 글꼴 업데이트 릴리즈 때 함께 버전 태그를 붙여도 괜찮을지 알려주시면 감사하겠습니다!

Merge 이후에 기여해주신 부분을 readme에 수정해두겠습니다 :D 이렇게 빠르고 꼼꼼히 신경써주셔서 다시 한번 진심으로 감사드립니다! 🥰

2023-02-06 15:34 UTC, black7375 commented on .github/workflows/generate.yml
> +        done
만약 줄어든 다이나믹 서브셋 글꼴을 배포하시고 싶으시면 바로 릴리즈를 하시면 될 것 같아요.
반대로 나중에 한꺼번에 처리하시고 싶으시면 다음 글꼴 업데이트후에 릴리즈 하시면 되구요!!

2023-02-07 15:55 UTC, merged

2023-02-07 15:55 UTC, orioncactus commented
이번에도 소중한 시간을 Pretendard 자동화 개선에 힘써주시고, 또 오랜 시간이 걸렸음에도 모두 꼼꼼히 확인해주신 @black7375님, 그리고 더 나은 방법을 제안해주신 @sudosubin님께 모두 진심으로 감사드립니다. 덕분에 더욱 수월하고 쾌적하게 에셋을 제작하고 관리할 수 있을 것 같습니다 ☺️ 적용되었습니다! 🚀