사용하는 곳 이미지 깨짐 수정 및 이미지 저장 구조 변경
orioncactus/pretendard pull request #202
Opened 2024-07-14 13:48 UTC by soulee-dev

# 문제점
![Screenshot 2024-07-14 181637](https://github.com/user-attachments/assets/93f61faa-99b4-4506-9e19-8f6d0febcd13)
`elice, 월급쟁이부자들, QANDA, 콴다과외` 네 개의 이미지가 정상적으로 로딩 되지 않고 있습니다.

<details>
<summary>로고 이미지 추가 관련 이슈</summary>
#119 
#107
#113 
#134
#150 
#154 
#155 
#172 
</details>

기존 이슈들을 분석한 결과 기여자에 따라 방식이 **천차만별**로, Issue나 PR에 이미지를 올려 링크를 따오거나, 자신의 레포지토리에 올리는 등 다양한 방식으로 기여를 해왔다는 것을 확인 할 수 있었습니다.

이에 따라 일부 Repo가 Private으로 바뀌거나, Github의 정책이 바뀜에 따라 이미지가 정상적으로 로딩 되지 않은 것 으로 추측됩니다.

# 변경점
![Screenshot 2024-07-14 220745](https://github.com/user-attachments/assets/4b2d08ec-2fe2-49f6-9697-1e07ce29311b)

1. Pretendard Repo에 직접 이미지 저장 하도록 변경 하였습니다.
2. 기존 이미지를 Migration 해오고, img태그에 있는 Pretendard Repo에서 직접 불러올 수 있도록 src를 모두 변경 하였습니다.

이렇게 하여 이미지 관리를 일원화 하고, 각자의 Repo의 상태나 Github 정책 변경 등에 대한 영향을 덜 받게 됩니다.
Github 자체에서 owner 이름이 바뀐 경우에도 자동 리다이렉션 되기 때문에 더 안정적인 이미지 저장 구조를 갖게 됩니다.

Pretendard 폰트 항상 잘 쓰고 있습니다! 정말 감사합니다!!

2024-07-17 05:21 UTC, black7375 approved these changes
좋은 변경 같습니다.

2024-07-17 07:08 UTC, soulee-dev commented
기존에 사용하던 img 태그를 몇가지 갖고 왔습니다.
보시다시피, 사용자나, 추가 시기별로 다 다른 링크를 갖고 있어 추후 관리하는데에 어려움이 생길거라고 생각이 듭니다.

```html
<img src="https://user-images.githubusercontent.com/7247848/148688031-f868235e-f5d6-4157-a4e5-a1e2e0c1214d.png" align="center" height="50" alt="썬데이나마스떼" hspace="16">
  
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/7247848/238135121-2f677a50-d00b-4db9-91aa-b95fdde224d0.png" align="center" height="50" alt="TECHIT" hspace="16">

<img src="https://github.com/orioncactus/pretendard/assets/3013607/087e1c34-6192-4604-8697-4ae1f3ea1a61" align="center" height="50" alt="BBQ 치킨" hspace="16">

<img src="https://github.com/kms0219kms/pretendard/assets/67222970/3f72324d-fff3-46ab-bc56-ce0f4cb70884" align="center" height="32" alt="elice" hspace="16">
 ```

2024-07-29 13:44 UTC, orioncactus commented
@soulee-dev 님 안녕하세요! 언젠간 해야 하는 작업이었는데 이렇게 소중한 시간을 써주시고 Pretendard 문서화에 기여해주셔서 감사드립니다! 한번 확인해보고 코멘트를 드려보겠습니다.

2024-07-29 13:46 UTC, soulee-dev commented
@orioncactus 확인해 주셔서 감사합니다! Pretendard 정말 잘 쓰고 있습니다.
한국 디자인 역사의 한 획을 그었다 해도 과언이 아닙니다.

2024-07-29 13:46 UTC, orioncactus requested changes

2024-07-29 13:46 UTC, orioncactus commented on packages/pretendard/README.md
> +   <img align="center" alt="미리캔버스" height="50" hspace="16" src="https://github-production-user-asset-6210df.s3.amazonaws.com/7247848/238135191-13ce5c74-e5e3-4b3c-a964-77d88115ce2e.png"/>
애셋에는 미리캔버스가 추가되어 있는데, 이 부분에는 반영이 안 되어서, 시간 되실 때 이 부분만 대응해주시면 바로 머지하겠습니다! ✨

2024-07-29 13:55 UTC, soulee-dev commented on packages/pretendard/README.md
> +   <img align="center" alt="미리캔버스" height="50" hspace="16" src="https://github-production-user-asset-6210df.s3.amazonaws.com/7247848/238135191-13ce5c74-e5e3-4b3c-a964-77d88115ce2e.png"/>
```html
<a href="https://www.miricanvas.com" target="_blank">
   <img align="center" alt="미리캔버스" height="50" hspace="16" src="https://raw.githubusercontent.com/orioncactus/pretendard/main/docs/images/logo/light/%EB%AF%B8%EB%A6%AC%EC%BA%94%EB%B2%84%EC%8A%A4%0A.png"/>
</a>
```

@orioncactus 
위와 같이 변경하여 커밋 하였습니다. 확인 부탁드립니다!

2024-07-29 13:59 UTC, orioncactus approved these changes

2024-07-29 14:06 UTC, merged

2024-07-29 14:06 UTC, orioncactus commented
굉장히 빠르게 확인해주시고 대응해주셔서 진심으로 감사드립니다! 적용되었습니다 🥰

추가적으로 시간이 될 때 기여자 섹션에 기여 내용을 추가해두겠습니다 :D 이렇게 도와주셔서 다시 한번 감사드립니다!

2024-07-29 14:17 UTC, soulee-dev commented
![IMG_0077](https://github.com/user-attachments/assets/dcadba4b-c64b-46af-bae4-ce30f42e4597)
정상적으로 이미지 잘 나오는걸 확인 했습니다.
그런데 제가 미리캔버스를 추가하면서 오탈자가 들어갔나보군요 ..ㅜ
미리캔버스만 안뜨고 있어서, 시간 날때 PR 올리도록 하겠습니다!

`https://raw.githubusercontent.com/orioncactus/pretendard/main/docs/images/logo/light/%EB%AF%B8%EB%A6%AC%EC%BA%94%EB%B2%84%EC%8A%A4.png`