[#90] 가변 폰트의 웹폰트 다이나믹 서브셋 제공
orioncactus/pretendard pull request #91
Opened 2022-08-13 12:23 UTC by hiddenest

## 개요
가변 폰트(Variable Font)도 다이나믹 서브셋을 적용하여 최신 웹 환경에서 더 적은 용량으로 폰트를 불러와 사용할 수 있도록 합니다.
자세한 내용은 #90 을 참조해주세요.

## 변경사항
- subset-utils 에서 kinds가 "dynamic"일 때, variable 여부를 받을 수 있도록 합니다.
- variable 여부에 따라 INPUT_PATH, DIST_PATH, CSS 파일명을 수정합니다.
- 각 폰트 패키지 내의 dist/web/variable 내에 템플릿 CSS를 추가합니다.

## 테스트 가능한 웹폰트 스타일시트
#### Pretendard
```
https://cdn.jsdelivr.net/gh/hiddenest/pretendard@c6058d5fdd9374f8d7f9e11fe7496984df8a7c81/dist/web/variable/PretendardVariable-subset.css
```
#### Pretendard JP
```
https://cdn.jsdelivr.net/gh/hiddenest/pretendard@c6058d5fdd9374f8d7f9e11fe7496984df8a7c81/dist/web/variable/PretendardJPVariable-subset.css
```
#### Pretendard Std
```
https://cdn.jsdelivr.net/gh/hiddenest/pretendard@c6058d5fdd9374f8d7f9e11fe7496984df8a7c81/dist/web/variable/PretendardStdVariable-subset.css
```

2022-08-13 12:23 UTC, hiddenest commented
@orioncactus @kms0219kms 혹시 시간이 되실 때 리뷰를 부탁드려도 괜찮을까요?

2022-08-14 00:07 UTC, orioncactus commented
Pretendard 웹폰트 용량 개선을 위해 시간을 써주시고 기여해주셔서 진심으로 감사드립니다! 저도 기여해주신 환경을 여러 브라우저에서 테스트해보고 문제가 없는지 확인해보겠습니다!

2022-08-14 06:46 UTC, hiddenest commented
@black7375 코드 리뷰해주셔서 감사합니다. 말씀해주신 내용을 반영하여 코드 업데이트하였습니다 :)

2022-08-14 07:19 UTC, black7375 approved these changes

2022-08-14 07:20 UTC, black7375 commented
좋아보입니다!!

2022-08-15 05:08 UTC, kms0219kms commented
저도 찬성합니다! 마침 기다리던 거라서요 ㅎㅎ

2022-08-22 01:03 UTC, orioncactus commented
@hiddenest님, 확인이 늦어 죄송합니다! 그리고 꼼꼼히 코드를 확인해주신 @black7375님과 @kms0219kms님께 감사드립니다!

### 질문 

1. 스타일시트를 확인해보니 `PretendardVariable-subset.css` 파일에서 중복된 unicode-range 정의가(1번과 93번 등) 있는데요, 이 부분은 제가 static에 있는 dynamic subset과 같이 수정하면 될까요?
2. 파일 이름도 static에 있는 것과 비슷하게 맞추기 위해 `PretendardVariable-subset`과 같은 이름을 `pretendardvariable-dynamic-subset`처럼 바꾸는 것은 어떨까 싶은데요, 전자와 같이 구성한 이유가 있는지 궁금합니다!

### Merge 전 체크리스트

그리고 제가 해야 할 체크리스트도 적어보았습니다. 아래 사항들은 오늘 밤에 확인하겠습니다!

- [ ] 추가된 파일 확인
- [ ] 브라우저 호환성 확인
- [x] OpenType 기능 확인
- [ ] 문서 업데이트
- [ ] 버전 업데이트

2022-08-22 08:22 UTC, hiddenest commented
> @hiddenest님, 확인이 늦어 죄송합니다! 그리고 꼼꼼히 코드를 확인해주신 @black7375님과 @kms0219kms님께 감사드립니다!
> 
> ### 질문
> 1. 스타일시트를 확인해보니 `PretendardVariable-subset.css` 파일에서 중복된 unicode-range 정의가(1번과 93번 등) 있는데요, 이 부분은 제가 static에 있는 dynamic subset과 같이 수정하면 될까요?
> 2. 파일 이름도 static에 있는 것과 비슷하게 맞추기 위해 `PretendardVariable-subset`과 같은 이름을 `pretendardvariable-dynamic-subset`처럼 바꾸는 것은 어떨까 싶은데요, 전자와 같이 구성한 이유가 있는지 궁금합니다!
> 
> ### Merge 전 체크리스트
> 그리고 제가 해야 할 체크리스트도 적어보았습니다. 아래 사항들은 오늘 밤에 확인하겠습니다!
> 
> * [ ]  추가된 파일 확인
> * [ ]  브라우저 호환성 확인
> * [x]  OpenType 기능 확인
> 
> ### Merge 이후 체크리스트
> * 문서 업데이트
> * 버전 업데이트

@orioncactus 안녕하세요, 형진님!
1. 네, 동일하게 수정해주시면 될 것 같습니다. 동시에, Variable Font와 Static Font 간의 다이나믹 서브셋 차이가 있는 항목들이 있다보니, 해당 부분을 그대로 적용해도 되는지 저도 체크해보겠습니다.
2. 아마 큰 생각이 있지는 않았을겁니다ㅋㅋ 수정해두겠습니다!

2022-08-22 14:23 UTC, orioncactus commented
@hiddenest macOS 및 Windows에서 모든 브라우저 테스트도 마쳤습니다! 에셋 모두 문제 없습니다 :+1: 1번과 2번만 해결하고, 마지막으로 제가 빌드 테스트만 해보면 merge할 수 있을 것 같습니다! 여담이지만, 이번 기여로 다이나믹 서브셋 용량을 기존 대비 최대 1/10 정도로 절약해 사용할 수 있는 것을 생각하면 정말 멋진 작업인 것 같습니다 🤩 저도 문제 없이 적용될 수 있도록 힘쓰겠습니다 💪

1번과 2번 수정은 어떻게 하는 게 좋을까요? 제가 [hiddenest:main](https://github.com/hiddenest/pretendard)에 PR을 하려고 해보았는데 불가능한 듯해서, merge 이후에 제가 수정하면 될지 궁금합니다!

2022-08-22 14:24 UTC, orioncactus requested changes
macOS 및 Windows에서 모든 브라우저 테스트도 마쳤습니다! 에셋 모두 문제 없습니다 👍 1번과 2번만 해결하고, 마지막으로 제가 빌드 테스트만 해보면 merge할 수 있을 것 같습니다! 여담이지만, 이번 기여로 다이나믹 서브셋 용량을 기존 대비 최대 1/10 정도로 절약해 사용할 수 있는 것을 생각하면 정말 멋진 작업인 것 같습니다 🤩 저도 문제 없이 적용될 수 있도록 힘쓰겠습니다 💪

이제 본론인데요, 1번과 2번 수정은 어떻게 하는 게 좋을까요? 제가 [hiddenest:main](https://github.com/hiddenest/pretendard)에 PR을 하려고 해보았는데 불가능한 듯해서, merge 이후에 제가 수정하면 될지 궁금합니다!

2022-08-22 19:26 UTC, black7375 commented
만약 git cli를 사용하신다면 이렇게 하시면 됩니다.

```shell
# 0. 레포 클론 또는 업데이트
git clone https://github.com/orioncactus/pretendard.git # 클론
git pull                                                # 이미 존재할 경우 업데이트

# 1. variable-dynamic 라는 브랜치 생성 및 전환 (임의의 이름을 사용했습니다)
git checkout -b variable-dynamic

# 2. hiddenest 님 레포 주소를 upstream이란 이름으로 추가 (역시 임의의 이름)
git remote add upstream https://github.com/hiddenest/pretendard.git

# 3. hiddenest 님 변경사항 받아오기
git pull upstream main

# 4. 파일 수정후 커밋
# 커밋은 평소에 하시던 대로

# 5. 깃허브에 업로드
git push origin variable-dynamic
```

6. 업로드 된 주소로 간 후 풀리퀘스트 생성
https://github.com/orioncactus/pretendard/tree/variable-dynamic

2022-08-23 00:55 UTC, orioncactus commented
> 만약 git cli를 사용하신다면 이렇게 하시면 됩니다.
> 
> ```shell
> # 0. 레포 클론 또는 업데이트
> git clone https://github.com/orioncactus/pretendard.git # 클론
> git pull                                                # 이미 존재할 경우 업데이트
> 
> # 1. variable-dynamic 라는 브랜치 생성 및 전환 (임의의 이름을 사용했습니다)
> git checkout -b variable-dynamic
> 
> # 2. hiddenest 님 레포 주소를 upstream이란 이름으로 추가 (역시 임의의 이름)
> git remote add upstream https://github.com/hiddenest/pretendard.git
> 
> # 3. hiddenest 님 변경사항 받아오기
> git pull upstream main
> 
> # 4. 파일 수정후 커밋
> # 커밋은 평소에 하시던 대로
> 
> # 5. 깃허브에 업로드
> git push origin variable-dynamic
> ```
> 
> 6. 업로드 된 주소로 간 후 풀리퀘스트 생성
>    https://github.com/orioncactus/pretendard/tree/variable-dynamic

오! 알려주셔서 감사합니다! 말씀하신대로 해보겠습니다 🔥

2022-08-31 06:34 UTC, hiddenest commented
@orioncactus 형진님! 업무가 바빠 많이 늦었습니다만, 일단 말씀해주신 내용 반영해두었습니다. 확인을 부탁드려도 될까요?

2022-09-01 14:39 UTC, orioncactus commented
@hiddenest 소중한 시간을 내주시고 작업해주셔서 정말 감사드립니다! 주말에 꼼꼼히 확인해본 다음에 다시 알려드리겠습니다!

2022-09-05 15:07 UTC, orioncactus commented
@hiddenest 네이밍 컨벤션을 맞추기 위한 Pull Request를 https://github.com/hiddenest/pretendard/pull/2 에 올렸습니다! 시간되실 때 확인해주시면 감사하겠습니다! 🔥

2022-09-07 14:30 UTC, hiddenest commented
> @hiddenest님, 시간을 내주셔서 확인해주시고 merge해주셔서 감사드립니다! PR에서 말씀해주신 것처럼  `packages` 안에서 Variable용 css는 `dynamic-subset.ts`에서 unicode-range를 읽을 때 폰트 이름과 같아야 다이나믹 서브셋이 생성될 수 있어서 이름 수정이 불가능한 상태군요 🤔
> 
> 
> 
> 아니면, `dynamic-subset.ts` 파일에서 variable일 때 `-subset`이 붙는 규칙만 빼서 `PretendardStdVariable.css`와 같이 생성되게 하고, static에서 관리하던 것처럼 수동으로 `pretendardvariable-std-dynamic-subset.css`와 같이 파일을 추가해서 관리하는 것이 나을까 싶은데, @hiddenest님의 의견은 어떠신가요? static에서와는 다른 파일명과 규칙이 살짝 걸려 여쭤봅니다..!

@orioncactus 음... 제가 제대로 이해한 것이 맞을까요?
- dynamic-subset에서 Variable인 CSS 파일을 찾을때 `-subset` 뒤에 안붙여도 되게 하기
- (생각해보니 위의 작업이 되면, packages 안의 dist/web/variable 안에는 pretendardvariable~.css 파일을 두지 않아도 되는게 아닌지?)

2022-09-07 14:53 UTC, orioncactus commented
제가 전달을 명확히 드리지 못해 죄송해요..! 🥲 정확히는 variable 다이나믹 서브셋 css 파일도 static 다이나믹 서브셋에서 쓰는 네이밍 규칙과 맞추기 위해 이렇게 관리하는 것은 어떤지 의견을 듣고 싶다는 이야기였습니다!

- `packages` 안에 있는 variable 다이나믹 서브셋 css 이름을 `PretendardStdVariable*.css`와 같이 둬야 한다면:
  - dynamic-subset에서 Variable인 CSS 파일을 찾을때 -subset 뒤에 안붙여도 되게 하고,
  - `PretendardStdVariable*.css`과 동일하지만, 이름만 `pretendardvariable-std-dynamic-subset.css`과 같이 되어 있는 파일을 수동으로 추가하는 식으로 관리하는 건 어떤지? (static 다이나믹 서브셋에서 `pretendard-std-dynamic-subset.css`를 수동으로 추가해 관리하는 것과 동일하게)

2022-09-08 14:56 UTC, orioncactus commented
@hiddenest님, 꼼꼼히 확인해주시고 알려주셔서 감사합니다! 말씀하신 것처럼 `-subset`을 뺐을 때에는 대소문자 구분이 불가능한 환경에서 `PretendardVariable.css`와 `pretendardvariable.css`가 충돌이 일어나는 문제가 있군요 😱

아니면, 명쾌한 해답은 아니지만 추후에 `pretendardvariable-subset.css`가 나올 수도 있음을 고려해, 아예 `-subset`을 `-VF`(Variable Font를 뜻하는 😂)으로 변경하는 것은 어떻게 생각하시나요? 제가 너무 수정 요청 쪽으로 피드백을 드리는 듯해 죄송스럽습니다 🙇 괜찮아 보인다면 제가 수정해 PR 보내드리겠습니다!

2022-09-09 06:49 UTC, hiddenest commented
@orioncactus 반영해두었습니다. 확인 부탁드립니다!

2022-09-09 13:47 UTC, orioncactus commented
@hiddenest님, 연휴 전날인데도 빠르게 확인해주시고 반영해주셔서 감사드립니다! 이제 거의 마무리 단계에 온 것 같아요 🥺 저도 테스트 빌드를 돌려보고, 다른 문제는 없는지 확인해보겠습니다!

2022-09-14 15:39 UTC, orioncactus commented
@hiddenest님, 기다려주셔서 감사합니다! 빌드 테스트를 진행해보니, 기여해주신 variable 다이나믹 서브셋 대응이 가능한 subset-utils를 통해 빌드할 때에도 모두 이상 없이 잘 생성되었습니다! 또 macOS Safari, Chrome, Firefox 및 Windows에서 Edge, Chrome, Firefox 모두 문제 없이 잘 표시됩니다 :fire:

마지막으로, `Pretendard Variable 소스 내의 중복 파일 제거` 커밋을 올리시면서, 빌드할 때의 결과와는 다르게 애셋이 생성되어서, 이를 원래대로 돌려놓는 Pull Request(https://github.com/hiddenest/pretendard/pull/3)를 올렸습니다! 시간 되실 때 확인해주시고, 문제 없다면 merge해주시면 감사하겠습니다!

소중한 시간에 이렇게 멋진 작업을 진행해주셔서 다시 한번 진심으로 감사드립니다!

2022-09-15 00:40 UTC, orioncactus approved these changes
Merge 준비 마쳤습니다! 🚀

2022-09-15 14:09 UTC, merged

2022-09-15 14:47 UTC, orioncactus commented
merge했습니다! 소중한 시간을 Pretendard Variable 다이나믹 서브셋을 위해 힘써주시고 기여해주셔서 다시 한번 감사드립니다! (▰ꈍ◡ꈍ▰)